package:
  name: libiges
  version:  1.0

source:  
  git_url: https://github.com/cbernardo/libIGES.git
  # path: ../
build:
requirements:
  build:
    - {{ compiler('cxx') }}
    - vs2019_win-64 [win]
    - ninja
    - cmake  
  host:

  run:

about:
  license: LGPL2.1

